apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-docs
  namespace: argocd
  labels:
    app.kubernetes.io/name: core-docs
    app.kubernetes.io/part-of: quatrain-community
  annotations:
    argocd-image-updater.argoproj.io/image-list: core-docs=ghcr.io/quatrain/core-docs
    argocd-image-updater.argoproj.io/core-docs.update-strategy: latest
    argocd-image-updater.argoproj.io/core-docs.allow-tags: regexp:^sha-[a-f0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tycho-ops/k8s-iac.git
    targetRevision: main
    path: k8s/stacks/core-docs/base
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
