apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
  - argocd-ingressroute.yml
  - lorawan-applicationset.yml
  - core-docs-application.yml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
  - target:
      kind: ConfigMap
      name: argocd-image-updater-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-image-updater-config
      data:
        registries.conf: |
          registries:
            - name: GitHub Container Registry
              api_url: https://ghcr.io
              prefix: ghcr.io
              ping: yes
              insecure: no
              credentials: secret:argocd/ghcr-creds#token
