apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lorawan-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tycho-ops/k8s-iac.git
    targetRevision: main
    path: k8s/stacks/lorawan/base
  destination:
    server: https://kubernetes.default.svc
    namespace: lorawan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
