apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-tls-cert
  namespace: git
spec:
  secretName: git-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: git.qtrn.io
  dnsNames:
    - git.qtrn.io
